django_4_0_test_website/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

django_4_0_test_website/mysite/website/urls.py
from email.mime import application
from django.urls import path

from .views import about, contact, index

app_name = 'website'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
]

django_4_0_test_website/mysite/website/models.py
import email
import uuid
from django.db import models

# Create your models here.
class Contact(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    title = models.CharField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __repr__(self) -> str:
        return f'Contacted by {self.name} {self.email} with title {self.title}'
    
    def __str__(self) -> str:
        return self.__repr__()

    class Meta:
        """Meta definition for Contact."""

        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

django_4_0_test_website/mysite/website/views.py
from django.http import HttpRequest, HttpResponse
from  django.contrib.messages import add_message, SUCCESS
from django.shortcuts import redirect, render

from .models import Contact

def index(request: HttpRequest) -> HttpResponse:
    return render(request=request, template_name='website/index.html', context={})

def contact(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        title = request.POST.get('title', '')
        message = request.POST.get('message', '')
        contact = Contact()
        contact.name = name
        contact.email = email
        contact.title = title
        contact.message = message
        contact.save(True)
        add_message(request, message='Thank you for your message', level=SUCCESS, extra_tags='success')
        return redirect('/')
        return render(request, 'website/thank_you.html', {'is_thank_you': True})
    return render(request=request, template_name='website/contact.html', context={})

def about(request: HttpRequest) -> HttpResponse:
    return render(request=request, template_name='website/about.html', context={})

django_4_0_test_website/mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>

    <title>{% block title %}Index  | {% endblock title %}My Website</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
  </head>
  <body>
    {% include 'partials/_navbar.html' %}
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <p{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} {% endif %}
        {{ message }}
    </p>
    {% endfor %}
</ul>
{% endif %}
    <div class="container mt-3">
        {% block content %}     
          <h1>Homepage</h1>     
        {% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

django_4_0_test_website/mysite/templates/partials/_navbar.html
{% load custom_tags %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'website:index' %}">Simon Cateau</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <!-- {% url 'website:index' as url %} -->
          <a {% active_link  'website:index' 'nav-link' %} href="{% url 'website:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a {% active_link  'website:about' 'nav-link' %} href="{% url 'website:about'  %}">About Me</a>
        </li>
        <li class="nav-item">
          <a {% active_link  'website:contact' 'nav-link' %} href="{% url 'website:contact' %}">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

django_4_0_test_website/mysite/website/templates/website/about.html
{% extends '../base.html' %}

{% block title %}About Me{% endblock title %}
    
{% block content %}
<h1>About Me</h1>    
{% endblock content %}

django_4_0_test_website/mysite/website/templates/website/contact.html
{% extends '../base.html' %}

{% block title %}About Me{% endblock title %}

{% block content %}
<h1>Contact</h1>
<form action="{% url 'website:contact' %}"  method="post" class="mb-5">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label" for="name">Name</label>
        <input class="form-control" type="text" name="name" id="name" placeholder="Enter your name"/>
      </div>
      <div class="mb-3">
        <label class="form-label" for="email">Email</label>
        <input class="form-control" type="email" name="email" id="email" placeholder="Enter your email"/>
      </div>
      <div class="mb-3">
        <label class="form-label" for="title">Title</label>
        <input class="form-control" type="text" name="title" id="title" placeholder="Enter the title of your message"/>
      </div>
      <div class="mb-3">
        <label class="form-label" for="message">Message</label>
        <textarea class="form-control" name="message" id="message" cols="30" rows="10"></textarea>
      </div>
      <div class="mb-3">
          <button type="submit" class="btn btn-primary">Send Message</button>
      </div>
</form>
{% endblock content %}

django_4_0_test_website/mysite/website/templates/website/index.html
{% extends '../base.html' %}

{% block content %}
<h1>Index</h1>    
{% endblock content %}

django_4_0_test_website/mysite/website/templates/website/thank_you.html
{% extends '../base.html' %}

{% block title %}Contact{% endblock title %}

{% block contact %}

{% if not is_thank_you %}
     
{% endif %}
    
    <h1>Contact</h1>
    <p>Thank you for your message.</p>
    <p>Go back to <a href="{% url 'website:index' %}">the homepage</a></p>
{% endblock contact %}